# -*- coding: utf-8 -*-
"""Copy of cs473_lab_week_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SO3yzPYdYSCPcOlJrDM3aLMNUIuw-3qM

<a href="https://colab.research.google.com/github/wingated/cs473/blob/main/labs/cs473_lab_week_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a><p><b>After clicking the "Open in Colab" link, copy the notebook to your own Google Drive before getting started, or it will not save your work</b></p>

# BYU CS 473 Lab Week 3

## Introduction:
In this lab, we'll explore both multivariate Gaussians and mixture models.

Mixture models are a powerful way to combine simple distributions to create complex distributions. Gaussian mixture modeling is a common place to start, because of the attractive theoretical properties of the model.

---
## Exercise #1: Data Generation
First, we'll practice sampling from a mixture model.
"""

import numpy as np

def sample_mm( Mu, Sigma, Weight ):
    # Mu is a list of length k. Each entry in the list is a dx1 vector, representing the mean of the corresponding mixture component
    # Sigma is a list of length k. Each entry is a dxd matrix, representing the corresponding covariance matrix
    # Weight is a list of length k. Each entry is a 1x1 scalar, representing the prior probability of that component
    #
    # Your code should return a single sample from the mixture. It should be a dx1 vector.

    # NOTE: the only sampling functions you can use are np.random.randn and np.random.choice (don't use np.random.multivariate_normal)
    # you can use other math functions as needed
    # HINT: Look at section 7.6.3 of the book for a way to sample from a Multivariate Gaussian

    # your code here

    #get your choice fo gaussian
    variable = np.random.choice(len(Mu), p=Weight)
    # variable = 0
    # print(f"Variable = {variable}")

    #grab the 'variableth' element in Mu
    #just grabbing the right parameter for the gaussian that we randomly chose
    our_mu = Mu[variable]
    # print(f"chosen mu = {our_mu}")

    #same with sigma
    our_sigma = Sigma[variable]
    # print(f"chosen sigma = {our_sigma}")

    #get L
    L = np.linalg.cholesky(our_sigma)
    # print(f"L = {L}")

    #get d
    d = our_mu.shape[0]
    # print(f"d = {d}")

    #get x
    x = np.random.normal(0,1,(d,1))
    # x = np.array([[1],[1]])
    # print(f"x = {x}")

    #get y
    y = L @ x + our_mu



    # print("y = : ")

    return y

# our mixture model

mu_1 = np.array([[0.22], [0.45]])
mu_2 = np.array([[0.5], [0.5]])
mu_3 = np.array([[0.77], [0.55]])
Mu = np.array([mu_1, mu_2, mu_3])

Sigma1 = np.array([[0.011, -0.01], [-0.01, 0.018]])
Sigma2 = np.array([[0.018, 0.01], [0.01, 0.011]])
Sigma3 = Sigma1
Sigma = np.array([Sigma1, Sigma2, Sigma3])

#putting in fake weights:
Weight = [1/3, 1/3, 1/3]

sample_mm(Mu, Sigma, Weight)

"""### Now, visualize the results and compare to the expected shapes
Here is some simple code for visualizing the level sets of a Gaussian
"""

import matplotlib.pyplot as plt
from scipy import linalg

def sigmaEllipse2D(mu, Sigma, level=3, npoints=128):
    """
    SIGMAELLIPSE2D generates x,y-points which lie on the ellipse describing
    a sigma level in the Gaussian density defined by mean and covariance.

    Input:
        MU          [2 x 1] Mean of the Gaussian density
        SIGMA       [2 x 2] Covariance matrix of the Gaussian density
        LEVEL       Which sigma level curve to plot. Can take any positive value,
                    but common choices are 1, 2 or 3. Default = 3.
        NPOINTS     Number of points on the ellipse to generate. Default = 32.

    Output:
        XY          [2 x npoints] matrix. First row holds x-coordinates, second
                    row holds the y-coordinates. First and last columns should
                    be the same point, to create a closed curve.
    """
    phi = np.linspace(0, 2 * np.pi, npoints)
    x = np.cos(phi)
    y = np.sin(phi)
    z = level * np.vstack((x, y))
    xy = mu + linalg.sqrtm(Sigma).dot(z)
    return xy

def plot_sigma_levels(mu, P):
    xy_1 = sigmaEllipse2D(mu, P, 0.25)
    xy_2 = sigmaEllipse2D(mu, P, 0.5)
    xy_3 = sigmaEllipse2D(mu, P, 0.75)
    xy_4 = sigmaEllipse2D(mu, P, 1)
    xy_5 = sigmaEllipse2D(mu, P, 1.25)
    xy_6 = sigmaEllipse2D(mu, P, 1.5)
    plt.plot(xy_1[0], xy_1[1])
    plt.plot(xy_2[0], xy_2[1])
    plt.plot(xy_3[0], xy_3[1])
    plt.plot(xy_4[0], xy_4[1])
    plt.plot(xy_5[0], xy_5[1])
    plt.plot(xy_6[0], xy_6[1])
    plt.plot(mu[0], mu[1], "ro")


for i in range( len(Mu) ):
    plot_sigma_levels(Mu[i], Sigma[i])

# sample data

N = 10000
results = [ sample_mm( Mu, Sigma, Weight ) for _ in range(N) ]

#
# Source - https://stackoverflow.com/q
# Posted by cuda_hpc80, modified by community. See post 'Timeline' for change history
# Retrieved 2026-01-22, License - CC BY-SA 4.0

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Fix: Convert the list of (2,1) arrays to a (10000,2) array for DataFrame
df = pd.DataFrame(np.squeeze(results), columns=['x', 'y'])

plt.figure(figsize=(10, 8))
sns.histplot(
    data=df,
    x="x", # Use 'x' and 'y' for column names
    y="y",
    cbar=True,         # Essential: Adds the color bar to show the 'Z' scale (count)
    cmap="mako",       # Aesthetic: Choose a gradient color map
    bins=30,           # Resolution: Higher = more detail, Lower = blockier
    thresh=None        # Optional: Set to 0 to show zero-count bins as background
)


plt.show() # Fix typo: 'shiow' to 'show'

# create a visualization of the data generated.  (perhaps something like sns.histplot?) Compare it to the level set plots in the previous cell. Do they match?
#

"""---
## Exercise #2: Marginals
One way to sample from a marginal distribution is to sample from a joint distribution, and throw away the variables that have been marginalized out.  We're going to compare empirical and exact distributions.

You should perform the following:

* Sample from a multivariate Gaussian p(x,y) with the given parameters
* For each sample, throw away the second number (the "y" coordinate)
* Plot the resulting distribution of datapoints

Then, use the equations in the book to calculate the exact density of the marginal distribution over the first dimension (the "x" variable)

"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Use these parameters
mu = np.array([[0.22], [0.45]])
sigma = np.array([[0.011, -0.01], [-0.01, 0.018]])

# YOUR CODE HERE
flat_mu = mu.flatten()
sample = np.random.multivariate_normal(flat_mu, sigma, 10000)

# print(sample)
all_x_from_sample = sample[:,0]
plot = sns.histplot(all_x_from_sample, kde=True, color='red')
plt.show()

# Sample
# Plot the empirical distribution of points (using, for example, a histogram plotting function)


# Plot the true density curve


def density_func(mu, std, y):
  density = (
      (1/(np.sqrt(2*np.pi*(std**2)))
      *np.exp(
          (-1/(2*(std**2))
          *((y-mu)**2)
      )
  )))
  return density

"""Now, calculate the density of several points using the marginal distribution over the "y" variable:

* Calculate p(y=0.39)
* Calculate p(y=0.2)
"""

# YOUR CODE HERE
all_y_from_sample = sample[:,1]

std_y = np.std(all_y_from_sample)
mu_y = np.mean(all_y_from_sample)

y_density = density_func(mu_y, std_y, .39)
print(f"P(.39) = {y_density}")
next_y = density_func(mu_y, std_y, .2)
print(f"P(.2) = {next_y}")

"""---
## Exercise #3: Conditionals
Now, let's explore the difference between marginals and conditionals.

Use the following joint distribution over 4 variables:
"""

import seaborn as sns

df = sns.load_dataset("penguins")

data = np.array( df[['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']])
data = data[~np.isnan(data).any(axis=1)] # drop any row with a NaN
data[:,2] /= 200 # scale some stuff
data[:,3] /= 3000

mu = np.mean( data, axis=0 )
sigma = np.cov( data.T )

print(mu)
print(sigma)

"""We'll assume that we have a multivariate normal distribution over 4 variables: p(x1,x2,x3,x4) = N( mu, sigma )

Now, we want to compute the mean of various conditionals
"""

# Compute the parameters of p(x2,x3)  (a marginal)

marg_mu_x2_x3 = mu[1:3]
marg_sigma_x2_x3 = sigma[1:3,1:3]

print( marg_mu_x2_x3 )
print( marg_sigma_x2_x3 )

# Compute the parameters or p(x2,x3|x1=34,x4=1.2)

#so we looked this up to understand the easy way and we are going to split
# our matrix up with (known) and (unknown) indices1

ind_a = [0,3] #KNOWNS
ind_b = [1,2] #UNKNOWNS
#these are going to be used quite a lot when cutting up our matrices, etc.

#set our knowns
x1 = 34
x4 = 1.2

#calculate what we need to calculate with the conditional vector mean equation
mu_b = mu[ind_b]
# print(mu_x2_x3)
x_b = data[ind_b]
print(f"x_b = {x_b}")
mu_a = mu[ind_a]
print(f"mu_a = {mu_a}")
x_a = np.array([34,1.2])


sigma_bb = sigma[np.ix_(ind_b,ind_b)]
print(f"sigma_bb = {sigma_bb}")
sigma_aa = sigma[np.ix_(ind_a,ind_a)]
# print(f"sigma_bb = {sigma_aa}")
sigma_ab = sigma[np.ix_(ind_a,ind_b)]
# print(f"sigma_bb = {sigma_ab}")
sigma_ba = sigma[np.ix_(ind_b,ind_a)]
# print(f"sigma_bb = {sigma_ba}")

cond_mu_x2_x3 = mu_b + (sigma_ba @ (np.linalg.inv(sigma_bb) @ (x_a - mu_a)))
# print(cond_mu_x2_x3)

cond_sigma_x2_x3 = sigma_aa - (sigma_ab @ (np.linalg.inv(sigma_bb) @ sigma_ba))
# print(cond_sigma_x2_x3)



print( cond_mu_x2_x3 )
print( cond_sigma_x2_x3 )

# Finally, calculate the density of a specific point:
def multivariate_density_function(mu, cov_mat, x):
  # print(cov_mat)
  k = len(mu)
  x = x.flatten()
  mu=mu.flatten()

  # left side
  det = np.linalg.det(cov_mat)
  norm_const = 1.0 / ( (2*np.pi)**(k/2) * np.sqrt(det) )

  # the exponent
  inv = np.linalg.inv(cov_mat)
  diff = x - mu
  exponent = -0.5 * (diff.T @ inv @ diff)

  return norm_const * np.exp(exponent)


# calculate p(x2=16, x3=0.99)
print(multivariate_density_function(mu_a, sigma_aa, np.array([16,.99])))

# calculate p(x2=16, x3=0.99 | x1=34,x4=1.2)
print(multivariate_density_function(cond_mu_x2_x3, cond_sigma_x2_x3, np.array([16,.99])))