# -*- coding: utf-8 -*-
"""Another copy of cs473_lab_week_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KE_EktFFLRuzAyJntkZJueMluNeiQE_n

<a href="https://colab.research.google.com/github/wingated/cs473/blob/main/labs/cs473_lab_week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a><p><b>After clicking the "Open in Colab" link, copy the notebook to your own Google Drive before getting started, or it will not save your work</b></p>

# BYU CS 473 Lab Week 5

## Introduction:

In this lab, we will carefully explore Bayesian reasoning using something called the "Numbers Game", a thought experiment from Josh Tenenbaum's PhD thesis.  You will implement a version of the numbers game, which will involve priors, likelihoods, posteriors, and posterior predictives.

See Ch 4.6 for the necessary Bayesian background.

[The numbers game is described in detail in this PDF](https://wingated.github.io/cs473/pdfs/numbers_game.pdf). NOTE that you only need up to section 2.5 (pg. 7), not the whole thing!

For this lab, your notebook should perform the following functions:

* Prompt the user for a set of numbers. (What happens if they only enter one number?)
* Display the prior, likelihood, and posterior for each concept
* Print the most likely concept
* Print the posterior predictive distribution over numbers

When you display your prior, likelihood, and posterior, your figure should look something like the ones in the book; my version is shown here:

![figure 1](https://raw.githubusercontent.com/wingated/cs473/main/labs/images/lab_week_5_image1.png)

Similarly, when you display the posterior predictive, your figure should look something like this:

![figure 2](https://raw.githubusercontent.com/wingated/cs473/main/labs/images/lab_week_5_image2.png)

---
## Grading standards   

Your notebook will be graded on the following:

* 10% Correctly formed & normalized prior
* 20% Correctly formed likelihood
* 30% Correctly formed & normalized posterior
* 30% Correctly formed & normalized posterior predictive
* 10% tidy and legible figures, including labeled axes

Remember: correct normalization may mean different things for different distributions!

---
## Description

Following the Bayesian Concept Learning example in the PDF, we're interested in reasoning about the origin of a set of numbers. We'll do this by placing a prior over a set of possible concepts (or “candidate origins”), and then use Bayes' law to construct a posterior distribution over concepts given some data.

For this lab, we will only consider numbers between 0 and 100, inclusive.

Your notebook should construct a set of possible number-game concepts (such as “even” or “odd”). These can be any set of concepts you want, but should include at least all of the concepts in the book (see, for example, Fig. 3.2). You must assign a prior probability to each concept.

To make grading easier on our incredible TA, your notebook should construct a set of possible number-game concepts that are the same as the concepts in in the image at the beginning of this notebook. You must assign a prior probability to each concept; to make grading easier, your prior should be:

```python
prior = numpy.ones(len(concepts))
prior[0] = 5
prior[1] = 5
prior[30] = .01
prior[31] = .01
prior = prior / numpy.sum(prior)
```

This prior distribution is $p(h)$.

You must then prompt the user for some data. This will just be a sequence of numbers, like 16, 2,4,6 or 4,9,25. This is *data*. You must then compute the likelihood of the *data*, given the hypothesis: $p(data|h)$.

**Important:** you can assume that each number in the data was sampled **independently**, and that each number was sampled **uniformly** from the set of all possible numbers *in that concept* **bold text**.

*Hint: what does that imply about the probability of sampling a given number from a concept with lots of possibilities, such as the all concept, vs. a concept with few possibilities, such as multiples of 10?*

Prepare a figure, as described in the Deliverable that illustrates your prior, the likelihood of the data for each concept, the posterior. Note: distributions should be properly normalized.

You must also prepare a figure showing the posterior predictive distribution. This distribution describes the probability that a number *x* is in the target concept (which we'll call *C*), given the data. (Note that we're drawing a subtle distinction between the true concept and a hypothesis). The book is somewhat unclear on this, but to do this, we marginalize out the specific hypothesis:

![equations](https://raw.githubusercontent.com/wingated/cs473/main/labs/images/lab_week_5_image3.png)

We've already computed the posterior $p(h|data)$, so we're only left with the term $p(\tilde{x} \in C|h)$. For this, just use an **indicator** function that returns 1 if $\tilde{x}$ is in **h**, and 0 otherwise.


*Hint: just like any other distribution, the posterior predictive is normalized - but it is not normalized as a function of $\tilde{x}$. So what is it normalized over?*

---
## Hints

You may find the following functions useful:
"""



import math as m

#multiples of 2-10

l1 = [i for i in range(101)]

l2 = [2*i for i in range(51)]

l3 = [i for i in range(101) if i%3==0]

l4 = [i for i in range(101) if i%4==0]

l5 = [i for i in range(101) if i%5==0]

l6 = [i for i in range(101) if i%6==0]

l7 = [i for i in range(101) if i%7==0]

l8 = [i for i in range(101) if i%8==0]

l9 = [i for i in range(101) if i%9==0]

l10 = [i for i in range(101) if i%10==0]

#powers of 2-10

l11 = [i for i in range(1,101) if m.log(i, 2)%1==0]

l12 = [i for i in range(1,101) if m.log(i, 3)%1==0]

l13 = [i for i in range(1,101) if m.log(i, 4)%1==0]

l14 = [i for i in range(1,101) if m.log(i, 5)%1==0]

l15 = [i for i in range(1,101) if m.log(i, 6)%1==0]

l16 = [i for i in range(1,101) if m.log(i, 7)%1==0]

l17 = [i for i in range(1,101) if m.log(i, 8)%1==0]

l18 = [i for i in range(1,101) if m.log(i, 9)%1==0]

l19 = [i for i in range(1,101) if m.log(i, 10)%1==0]

#primes

def is_prime(n):
    """Check if a number is prime."""
    if n <= 1:
        return False  # 0 and 1 are not prime numbers
    if n == 2:
        return True   # 2 is the only even prime number
    if n % 2 == 0:
        return False  # Other even numbers are not prime

    # Check for divisors from 3 up to the square root of n, skipping even numbers
    for i in range(3, int(m.sqrt(n)) + 1, 2):
        if n % i == 0:
            return False

    return True

l20 = [i for i in range(0,101) if is_prime(i)]

#composites

l21 = [i for i in range(0,101) if not is_prime(i)]

#odds

l22 = [i for i in range(0,101) if i%2==1]

#mod 3 == 1
l23 = [i for i in range(0,101) if i%3==1]
#mod3 == 2
l24 = [i for i in range(0,101) if i%3==2]
#mod 4 == 1
l25 = [i for i in range(0,101) if i%4==1]
#mod4 == 2
l26 = [i for i in range(0,101) if i%4==2]
#mod4 == 3
l27 = [i for i in range(0,101) if i%4==3]
#mod5 == 1
l28 = [i for i in range(0,101) if i%5==1]
#mod5 == 2
l29 = [i for i in range(0,101) if i%5==2]
#mod5 == 3
l30 = [i for i in range(0,101) if i%5==3]
#mod5 == 4
l31 = [i for i in range(0,101) if i%5==4]
#99 or less
l32 = [i for i in range(0,101)if i<=99]

h_space = [l1,l2,l3,l4,l5,l6,l7,l8,l9,l10,
                 l11,l12,l13,l14,l15,l16,l17,l18,l19,l20,
                 l21,l22,l23,l24,l25,l26,l27,l28,l29,l30,
                 l31,l32]

# print(possibilities[0])

#prior is supposed to NOT be uniform they said.

import numpy
prior = numpy.ones(len(h_space))
prior[0] = 5
prior[1] = 5
prior[30] = .01
prior[31] = .01
# print(h_space[31])
prior = prior / numpy.sum(prior)

total=0
for i in range(len(prior)):
  total+=prior[i]

for i in range(len(prior)):
  prior[i]/=total

# final_check = 0
# for i in range(len(prior)):
#   final_check += prior[i]
# print(final_check)

# GET THE NUMBERS AND TURN INTO LIST
numstr = input('Please enter a set of numbers: ')

numstrlst = numstr.split()

numlst = list(map(int, numstrlst))

# numlst = []
# for num in numstrlst:
#   numlst.append(int(num))

print(numlst)

#first we set the impossible hyps to zero likelihood
likelihood = h_space.copy()
for i in range(len(likelihood)):
  # print(hypP
  for num in numlst:
    # (print(num))
    if not num in likelihood[i]:
      # print(num)
      likelihood[i]=0
      break
    pass #skip to next hyp

print(f'WHATS LEFT: {likelihood}')

#likelihood should be the chance of getting numlst randomly from these hyps

#because the instructions say "sampled uniformly from the set of numbers in that concept"


for i in range(len(likelihood)):
  if isinstance(likelihood[i], list):
  #length of hyp
    length = len(likelihood[i])

    #uniform prob for a single number from this hypothesis
    unip_single_num = 1 / length

    # The likelihood of observing all numbers in numlst for this hypothesis
    # is (1/length) raised to the power of the number of items in numlst

    llh_for_hyp = unip_single_num ** len(numlst)
    likelihood[i]=llh_for_hyp

# #normalization actually isn't something we do for likelihood!!!!
# total_llh = 0
# for lh in likelihood:
#   total_llh+=lh
# for i in range(len(likelihood)):
#   likelihood[i]=likelihood[i]/total_llh
print(likelihood)

import numpy as np
#posterior
#this list stuff has been very annoying so im converting everything to arrays
likelihood_a = np.array(likelihood)
prior_a = np.array(prior)

posterior = np.zeros(len(likelihood))
posterior = likelihood_a*prior_a
#normalize
posterior = posterior/sum(posterior)
print(posterior)

#wow that was so much faster. bruh.

"""### Calculating the Posterior Predictive Distribution"""

import numpy as np
import matplotlib.pyplot as plt

# Initialize the posterior predictive distribution for numbers 0 to 100
posterior_predictive = np.zeros(101) # Numbers from 0 to 100 inclusive

# Iterate through each possible number x_tilde
for x_tilde in range(101):
    # For each x_tilde, sum over all hypotheses
    sum_over_hypotheses = 0
    for i, concept in enumerate(h_space):
        # P(x̃ ∈ C | h) is an indicator function
        if x_tilde in concept:
            # Add P(h | data) to the sum
            sum_over_hypotheses += posterior[i]

    posterior_predictive[x_tilde] = sum_over_hypotheses

# Normalize the posterior predictive distribution
# It should sum to 1 across all possible x_tilde values if it represents a probability distribution over x_tilde
posterior_predictive = posterior_predictive / np.sum(posterior_predictive)

print("Posterior Predictive Distribution (first 10 values):\n", posterior_predictive[:10])
print("Sum of Posterior Predictive Distribution:", np.sum(posterior_predictive))

"""### Displaying Prior, Likelihood, and Posterior"""

# Define concept names for better plotting labels
concept_names = [
    "All Numbers", "Multiples of 2", "Multiples of 3", "Multiples of 4", "Multiples of 5",
    "Multiples of 6", "Multiples of 7", "Multiples of 8", "Multiples of 9", "Multiples of 10",
    "Powers of 2", "Powers of 3", "Powers of 4", "Powers of 5", "Powers of 6",
    "Powers of 7", "Powers of 8", "Powers of 9", "Powers of 10", "Primes",
    "Composites", "Odds", "Mod 3 = 1", "Mod 3 = 2", "Mod 4 = 1",
    "Mod 4 = 2", "Mod 4 = 3", "Mod 5 = 1", "Mod 5 = 2", "Mod 5 = 3",
    "Mod 5 = 4", "Less than 99"
]

# Create a figure with three subplots
plt.figure(figsize=(15, 10))

# Subplot for Prior
plt.subplot(3, 1, 1) # 3 rows, 1 column, 1st plot
plt.bar(concept_names, prior_a)
plt.title('Prior Distribution P(h)')
plt.ylabel('Probability')
plt.xticks(rotation=90)
plt.tight_layout()

# Subplot for Likelihood
plt.subplot(3, 1, 2) # 3 rows, 1 column, 2nd plot
plt.bar(concept_names, likelihood_a)
plt.title('Likelihood P(data | h)')
plt.ylabel('Probability')
plt.xticks(rotation=90)
plt.tight_layout()

# Subplot for Posterior
plt.subplot(3, 1, 3) # 3 rows, 1 column, 3rd plot
plt.bar(concept_names, posterior)
plt.title('Posterior Distribution P(h | data)')
plt.ylabel('Probability')
plt.xticks(rotation=90)
plt.tight_layout()

plt.subplots_adjust(hspace=0.8) # Adjust vertical spacing between subplots
plt.show()

# Find and print the most likely concept
most_likely_concept_index = np.argmax(posterior)
most_likely_concept_name = concept_names[most_likely_concept_index]
most_likely_concept_prob = posterior[most_likely_concept_index]

print(f"\nThe most likely concept is: {most_likely_concept_name} (with a posterior probability of {most_likely_concept_prob:.4f})")

""" Posterior Predictive"""

plt.figure(figsize=(12, 6))
plt.bar(range(101), posterior_predictive)
plt.title('Posterior Predictive Distribution P(x̃ | data)')
plt.xlabel('Number (x̃)')
plt.ylabel('Probability')
plt.xlim(-1, 101) # Set x-axis limits to clearly show 0-100
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()