# -*- coding: utf-8 -*-
"""Copy of cs473_lab_week_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwkTmQu4hH5dgOR5F1GK0PTu0es5lrXb

<a href="https://colab.research.google.com/github/wingated/cs473/blob/main/labs/cs473_lab_week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a><p><b>After clicking the "Open in Colab" link, copy the notebook to your own Google Drive before getting started, or it will not save your work</b></p>

# BYU CS 473 Lab Week 4

## Introduction:
KL divergence is one of the most commonly used concepts in machine learning. Here, we'll explore the

---
## Exercise #1: Symmetry    

KL divergence is a *measure*, but not a *metric*. This means that while it satisfies some properties of things like a distance metric, it does not satisfy all of them.

For example, KL divergence is NOT symmetric. First, implement a function that calculates the KL divergence between two discrete distributions. Then,cCraft an example to demonstrate that it is not symmetric.
"""

import numpy as np

def kl(a,b):
    # a is a n-dimensional distribution
    # b is a n-dimensional distribution
    #
    # return: KL(a||b)
    sum = 0
    for n in range(len(a)):
      sum += a[n]*np.log(a[n]/b[n])

    return sum

# find an example where kl(a,b) != kl(b,a)
a = [.25,.25,.25,.25]
b = [.3, .2, .1, .4]

print(kl(a,b))
print(kl(b,a))

"""---
## Exercise #2: Triangle inequality

Another property that KL divergence does not satisfy is the triangle inequality, which states that

kl(a,c) <= kl(a,b)+kl(b,c)

Prove that KL divergence does not satisfy the triangle inequality by crafting a counter-example.
"""

a = [1,2,3]
b = [4,5,6]
c = [7,8,9]

print(kl(a,c) <= (kl(a,b)+kl(b,c)))

"""---
## Exercise #3: Proofs

Prove that:

1) kl(a,a) = 0
2) kl(a,b) >= 0

Extra credit:

3) kl(a,b) = 0 iff a==b

MY PROOFS ARE ATTTACHED WITH THE LAB ON LS!!!
"""