# -*- coding: utf-8 -*-
"""Copy of week_1_uncertainty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjWgqZVDWEODCd5jHEK8_IQud3Owu8sA

<a href="https://colab.research.google.com/github/wingated/cs473/blob/main/mini_labs/week_1_uncertainty.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# BYU CS 473 — Types of Uncertainty

In this assignment, you will explore **epistemic** and **aleatoric** uncertainty in machine learning.
You will use a small dataset to visualize predictions, compute uncertainty, and reflect on the differences between these two key concepts.

---
## Learning Goals
- Understand the difference between **epistemic** (knowledge/model) and **aleatoric** (data/noise) uncertainty
- Learn how to model uncertainty using probability distributions
- Implement uncertainty estimation with a softmax-based classifier
- Visualize how uncertainty appears in decision boundaries
- Practice interpreting results and reflecting on uncertainty in real-world ML tasks

## Part 1 — dataset
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generate a toy dataset
X, y = make_classification(
    n_samples=400, n_features=2, n_redundant=0, n_clusters_per_class=1,
    class_sep=1.0, random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

"""## Part 2 — Softmax Probabilities (Aleatoric Uncertainty)

Here you’ll train a logistic regression classifier and use its predicted probabilities to measure **aleatoric uncertainty**.
Aleatoric uncertainty shows up when points are near the decision boundary (probabilities close to 0.5).

"""

clf = LogisticRegression().fit(X_train, y_train)

probs = clf.predict_proba(X_test)
preds = clf.predict(X_test)

accuracy = accuracy_score(y_test, preds)
print("Accuracy:", accuracy)

"""### TODO:

Find the points that have the most uncertain predictions.  Think about this a little bit - can you come up with a way to quantify a "certain prediction" vs. an "uncertain prediction"?
"""

# XXX your code here

certainty = np.max(probs, axis=1)

uncertainty = 1 - certainty

# Show most uncertain predictions
most_uncertain_idx = np.argsort(-uncertainty)[:5]
print("Most uncertain samples (indices):", most_uncertain_idx)
print("Probabilities for those samples:\n", probs[most_uncertain_idx])

"""## Part 3 — Visualizing Uncertainty

---

### What is a decision boundary?  
A **decision boundary** is a line that a classifier learns to **separate different classes** of data.  
- Points on one side of the boundary are predicted as one class.  
- Points on the other side are predicted as another.  

In two dimensions, we can plot this boundary directly. The shaded regions in the visualization show the classifier’s predicted classes, while the dots are the actual data points.  

Where the dots overlap or cluster near the boundary, the classifier has more difficulty deciding — this is where we see **uncertainty**.  

- **Aleatoric uncertainty**: appears near the decision boundary, caused by noisy or overlapping data.  
- **Epistemic uncertainty**: occurs in regions far away from any training data (where the model is unsure because it has not “seen” those inputs before).  

---

When you look at the plot:  
- The **shaded regions** represent the classifier’s predictions.  
- The **solid boundary line** shows where the model is exactly 50/50 between classes.  
- The **data points** show the ground-truth labels.  

</details>

"""

def plot_decision_boundary(clf, X, y, title="Decision boundary"):
    h = .02
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    plt.contourf(xx, yy, Z, alpha=0.3)
    plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors="k")
    plt.title(title)
    plt.show()

plot_decision_boundary(clf, X_train, y_train, "Aleatoric uncertainty example")

"""## Part 4 — Epistemic Uncertainty (via Model Variation)

Epistemic uncertainty can be explored by varying the model or subsampling the training data.
We’ll train multiple logistic regression models on bootstrapped samples and measure the variation in predictions.

"""

from sklearn.utils import resample

n_models = 20
all_probs = []

for i in range(n_models):
    X_boot, y_boot = resample(X_train, y_train, replace=True, random_state=i)
    clf_boot = LogisticRegression().fit(X_boot, y_boot)
    all_probs.append(clf_boot.predict_proba(X_test))

all_probs = np.array(all_probs)  # shape (n_models, n_samples, n_classes)

# Epistemic uncertainty = variance across models
epistemic_uncertainty = all_probs.var(axis=0).mean(axis=1)

print("Sample epistemic uncertainties:", epistemic_uncertainty[:10])

"""### TODO

Now, using the plot_decision_boundary function from Part 3 and the code in Part 4, can you come up with a way to visualize the uncertainty in the decision boundary?
"""

# XXX your code here

#copy paste from da function babyyyyyy
h = .02
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                      np.arange(y_min, y_max, h))

n_models = 20
grid_probs = []

grid_points = np.c_[xx.ravel(), yy.ravel()]

for i in range(n_models):
  #resample and retrain like before
  X_boot, y_boot = resample(X_train, y_train, replace=True, random_state=i)
  clf_boot = LogisticRegression().fit(X_boot, y_boot)


  preds = clf_boot.predict_proba(grid_points)[:, 1]
  grid_probs.append(preds)

grid_probs = np.array(grid_probs)

#okay now we have the probabilities for every single model

#pull the variance (this is basically uncertainty per pixel)
uncertainty_map = grid_probs.var(axis=0)
#fix the shape
uncertainty_map = uncertainty_map.reshape(xx.shape)


plt.figure(figsize=(10, 6))

# use contour map for sexiest result
plt.contourf(xx, yy, uncertainty_map, alpha=.9)
plt.colorbar(label="Epistemic Uncertainty (Variance)")

# Overlay the original data points
plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors="k", cmap="coolwarm", alpha=0.6)

plt.title("Epistemic Uncertainty near Decision Boundary")
plt.show()

"""## Part 5 — Reflection

Answer the following in 2–3 sentences each:

1. Which type of uncertainty did you observe near the decision boundary? Why?

I saw higher levels of uncertainty on the edges (left and right) on the boundary ends. This is going to be Epistemic. We don't have data over there, so it's our model's problem that it doesnt decide anything. Now, very close to boundary, just where the points start to touch the uncertainty, this is aleatoric, because we have a lot of data there, but sitll have uncertainty, so theres too much noise to be accurate. the data will never show a clean enough cut for our model to be capable of telling apart.

2. How did epistemic uncertainty change across different bootstrap models?

It was relatively stable. Since the samples were as such:Sample epistemic uncertainties: [1.18561488e-04 4.90491887e-05 1.16268281e-03 4.66090737e-05
 8.28161886e-04 1.47239788e-04 1.09531739e-03 4.51186822e-04
 1.24974306e-04 1.39166442e-04] we know that variance was really small between the models. uncertainty was basically identical

3. Give a real-world example where epistemic uncertainty dominates, and one where aleatoric uncertainty dominates.  

epistemic: self driving cars are fine in clean flat roads. but they don't do well in mountains or offroad.

aleatoric: correctly predicting a coin toss

"""