# -*- coding: utf-8 -*-
"""Copy of week_4_empirical_risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHcWFsrqVZk5QuIG0IxXrLArwF3aFQlZ

<a href="https://colab.research.google.com/github/wingated/cs473/blob/main/mini_labs/week_4_empirical_risk.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# BYU CS 473 — Empirical Risk Minimization and Model Evaluation

In this assignment, you will learn how empirical risk minimization relates to model performance, and how concepts like approximation error, estimation error, regularization, structural risk minimization, and cross-validation help build better models.

---

## Learning Goals
- Understand **approximation error** vs **estimation error**
- Understand **regularized risk minimization**
- Understand **structural risk minimization**
- Apply **cross-validation** to evaluate models

## 1. Empirical Risk & Error Decomposition

- **Empirical Risk Minimization (ERM):** we choose a hypothesis that minimizes the average loss on training data.  
- **Approximation Error:** error due to limited model class (e.g., linear models can’t fit curved patterns).  
- **Estimation Error:** error due to limited data or overfitting.

$\text{Total Error} = \text{Approximation Error} + \text{Estimation Error}$
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

# Generate nonlinear data
np.random.seed(0)
X = np.linspace(-3, 3, 50).reshape(-1, 1)
y = np.sin(X) + np.random.normal(0, 0.1, X.shape)

# Linear fit (high approx. error, low est. error)
lin = LinearRegression().fit(X, y)
y_lin = lin.predict(X)

# Polynomial fit (low approx. error, higher est. error risk)
poly = PolynomialFeatures(degree=10)
X_poly = poly.fit_transform(X)
lin_poly = LinearRegression().fit(X_poly, y)
y_poly = lin_poly.predict(X_poly)

plt.scatter(X, y, label="Data")
plt.plot(X, y_lin, label="Linear Fit")
plt.plot(X, y_poly, label="Polynomial Fit")
plt.legend()
plt.title("Approximation Error vs Estimation Error Example")
plt.show()

"""### Exercise 1
- Fit polynomial models of degree 2, 5, and 15 to the same data.  
- Compare their training error and test error (use a held-out test set).  
- Which models show more approximation error? Which show more estimation error?

"""

# Your code here

data_x = np.linspace(-5,5,100).reshape(-1,1)
data_y = 3*np.sin(data_x/2)+np.random.normal(0,3, data_x.shape)

OLS2 = LinearRegression().fit(data_x,data_y)
OLS2_y = OLS2.predict(data_x)

# Polynomial fit (low approx. error, higher est. error risk)
poly2 = PolynomialFeatures(degree=2)
X2_poly = poly.fit_transform(data_x)
lin2_poly = LinearRegression().fit(X2_poly, data_y)
y2_poly = lin2_poly.predict(X2_poly)

poly5 = PolynomialFeatures(degree=5)
X5_poly = poly.fit_transform(data_x)
lin5_poly = LinearRegression().fit(X5_poly, data_y)
y5_poly = lin5_poly.predict(X5_poly)

poly15 = PolynomialFeatures(degree=15)
X15_poly = poly.fit_transform(data_x)
lin15_poly = LinearRegression().fit(X15_poly, data_y)
y15_poly = lin15_poly.predict(X15_poly)

# poly50 = PolynomialFeatures(degree=50)
# X50_poly = poly.fit_transform(data_x)
# lin50_poly = LinearRegression().fit(X50_poly, data_y)
# y50_poly = lin50_poly.predict(X50_poly)


plt.scatter(data_x, data_y, label="data")
plt.plot(data_x,OLS2_y, label='linear fit')
plt.plot(data_x, y2_poly, label='quadratic fit')
plt.plot(data_x, y5_poly, label='5th degree approx.')
plt.plot(data_x, y15_poly, label='15th degree approx.')
# plt.plot(data_x, y50_poly, label='insane 50 degree')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.title('sine-wave-ish data')
plt.show()

"""Our high-degree polynomial is prone to overfitting == high estimation error

low degree polynomials are less likely to overfit and more likely to not be able to fit at all, which is epistemic == approximation error

## 2. Regularized Risk

To reduce overfitting, we add a penalty term to the empirical risk:

$R_{\text{reg}}(h) = R_{\text{emp}}(h) + \lambda \cdot \Omega(h)$

- $R_{\text{emp}}$: training error  
- $\Omega(h)$: complexity of hypothesis (e.g., large weights)  
- $\lambda$: regularization strength  

Examples: **Ridge (L2)**, **Lasso (L1)**.
"""

from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size=0.3, random_state=0)

ridge = Ridge(alpha=.1).fit(X_train, y_train)
lasso = Lasso(alpha=.01, max_iter=10000).fit(X_train, y_train)

print("Ridge test error:", mean_squared_error(y_test, ridge.predict(X_test)))
print("Lasso test error:", mean_squared_error(y_test, lasso.predict(X_test)))

"""### Exercise 2
Experiment with different values of λ for Ridge regression.  
- How does increasing λ affect training error?  
- How does it affect test error?  
- Why?

.1:
Ridge test error: 0.009857671344362615

alpha=1
Ridge test error: 0.015494279161805081

10:
Ridge test error: 0.07503268485492062

100:
Ridge test error: 0.21151747815925775

1000:
0.35712397776329746

LASSO:


.01:
Lasso test error: 0.010718201901479476


.1:
Lasso test error: 0.055022128422353586

1:
Lasso test error: 0.42591250210169945

10:
Lasso test error: 0.46922893918703906

100:
Lasso test error: 0.507274059723068

higher lambda leads to higher test error. It simply rates a model more harshly for high complexity (if it is higher rather than lower). This ends up making our training error low when lambda is low, and testing error high when lambda is high, because low lambda means we don't care about overfitting. It'll get everything. High lambda will underfit, also leading to high test error. So we are in a battle of sacrificing accuracy in training data to reduce complexity and gain accuracy in testing data.

Your response here

## 3. Structural Risk Minimization

ERM chooses the best hypothesis within a model class.  
**Structural Risk Minimization (SRM)** considers a sequence of model classes of increasing complexity, balancing fit and capacity.

- Small models → high approximation error, low estimation error.  
- Large models → low approximation error, high estimation error risk.  

SRM chooses the model class with best **generalization**.

### Exercise 3
Train polynomial regressors with degrees from 1 to 15.  
- Plot training and test error against model degree.  
- Which degree minimizes test error?  
- How does this illustrate SRM?
"""

#first lets make some data

x_data_train = np.linspace(-3,3,100).reshape(-1,1)
y_data_train = np.cos(x_data_train)**2 + np.random.normal(0,.7,x_data_train.shape)

#now some testing data based off true parameters
x_data_test = np.linspace(-3,3,30).reshape(-1,1)
y_data_test = np.cos(x_data_test)**2 + np.random.normal(0,.7,x_data_test.shape)


#now we are going to make the 15 models
degrees = range(1,16)

#collect errors here
train_errors = []
test_errors = []

plt.figure(figsize=(12,6))

for degree in degrees:
  poly_features = PolynomialFeatures(degree=degree)
  x_train_poly = poly_features.fit_transform(x_data_train)
  x_test_poly = poly_features.fit_transform(x_data_test)

  model= LinearRegression()
  model.fit(x_train_poly, y_data_train)

  y_train_pred = model.predict(x_train_poly)
  y_test_pred = model.predict(x_test_poly)

  train_error = mean_squared_error(y_data_train, y_train_pred)
  test_error = mean_squared_error(y_data_test, y_test_pred)

  train_errors.append(train_error)
  test_errors.append(test_error)

  plt.plot(x_data_test, y_test_pred, label=f'degree-{degree}')




plt.scatter(x_data_test, y_data_test, color='red')
plt.scatter(x_data_train, y_data_train)
plt.legend()
plt.show()

plt.figure(figsize=(12,10))
plt.plot(degrees, train_errors, label='train error')
plt.plot(degrees, test_errors, label='test error')
plt.xticks(list(degrees))
plt.grid=(True)
plt.legend()
plt.show()

"""We can see here that test error goes down, but then back up as degree increases. anything past degree 8 is overfitting the data. This demonstrates the trade-off between approximation error(high when degree is low) and estimation error(high when degree is high).

SRM is when we pick the type of model that has the least error (structural, not having to do with the parameters yet). We can see here that there is certainly a range in scoring of these models.

## 4. Cross-Validation

Cross-validation estimates model performance by splitting data into multiple training/test folds.

- **k-fold cross-validation:** split data into k folds, train on k-1, test on 1, rotate.  
- Provides a more stable estimate of generalization error.
"""

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline

degrees = range(1, 8)
cv_scores = []

for d in degrees:
    model = make_pipeline(PolynomialFeatures(d), LinearRegression())
    scores = cross_val_score(model, X, y, cv=5, scoring="neg_mean_squared_error")
    cv_scores.append(-scores.mean())

plt.plot(degrees, cv_scores, marker="o")
plt.xlabel("Polynomial Degree")
plt.ylabel("Cross-Validation Error")
plt.title("Model Selection with Cross-Validation")
plt.show()

"""### Exercise 4
- Which polynomial degree minimizes cross-validation error?  
- How does this compare to training/test error without cross-validation?  
- Why is cross-validation more reliable?

It's actually really hard to tell. it looks like 1 degree minmimizes it. But that looks the same as degree 6.

When I cut off all of the high-error degrees, we seew that its a tie betwee 3 and 5.

This is a smaller preferred degree number than we get with normal training/test error, no cross validation.

I believe this is happening because models of size 6 and 7 are indeed overfitting, but because i had so many points in both the training and the testing sets, it didn't overfit. here, where we slice sets into smaller pieces (to cross-validate),  we aren't feeding the hgih-degree polynomials (tons of parameters) enough data. Also, we get to train on smaller sets but we both validate and train on every single point. Therefore, we don't have "important" points missed because they're stuck in the test set.

It also averages, which gets us closer to the truth (unbiased estimator)

## 5. Reflection

### Exercise 5
Answer in 2–3 sentences each:

1. What is the difference between approximation error and estimation error?  
2. How does regularization reduce overfitting?  
3. Why is cross-validation preferred over a single train/test split?

1. Approximation error is a results of choosing the wrong model. It is from underfitting (not optimizing the type of model from the set of all possible models,  because our model class is too narrow). Estimation error is a result of choosing too-complex of a model. it is overfitting the data (either because the parameters are too  many or the data too little).

2. Regularization specifically penalizes complexity in models. the higher the lambda, the more strict the penalization. We need a sweet spot model, and this is what the regularization does---allows us to have a framework for sacrificing complexity/training accuracy on behalf of simplicity/testing accuracy. We need simpler models to stop fitting noise and start generalizing the data.

3. A single train/test set has the possiblity of telling you your model is bad, when in reality the data just got unlucky. A different split of train/test wouldn't end up so badly. So when we average these, we get the expectation, which is going to be closer to the truth an our outlier training sets.
"""