# -*- coding: utf-8 -*-
"""Copy of week_3_correlation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1e0oUzhQ0UudqkspmWEcAf0cK1VvyFA

<a href="https://colab.research.google.com/github/wingated/cs473/blob/main/mini_labs/week_3_correlation.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# BYU CS 473 — Correlation, Causation, and Simpson’s Paradox

In this assignment, you will learn to distinguish between correlation, causation, and independence, and explore the concept of **Simpson’s Paradox**.

---

## Learning Goals
- Understand the difference between correlation and causation  
- Understand why correlation does not imply independence  
- Understand why correlation ≠ causation  
- Recognize and explain Simpson’s Paradox

## 1. Correlation

Correlation measures the strength and direction of a linear relationship between two variables.  

- Positive correlation → as one variable increases, the other tends to increase.  
- Negative correlation → as one increases, the other tends to decrease.  
- Zero correlation → no linear relationship.  

We use **Pearson’s correlation coefficient**:  
$r = \frac{\text{Cov}(X, Y)}{\sigma_X \sigma_Y}$
"""

import numpy as np
import matplotlib.pyplot as plt

# Example: positively correlated variables
x = np.random.normal(0, 1, 100)
y = 2 * x + np.random.normal(0, 1, 100)

plt.scatter(x, y)
plt.title("Positive Correlation Example")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

np.corrcoef(x, y)[0, 1]

"""### Exercise 1
Generate two negatively correlated variables and compute their correlation coefficient.  
Plot them with a scatterplot.

"""

# Your code here

indep = np.random.normal(0,1,100)
dep = 20-(5*indep) + np.random.normal(0,1,100)

plot = plt.scatter(indep,dep)
plt.title("attempted negative correlation lol")
plot

"""## 2. Correlation ≠ Independence

Two variables can be **uncorrelated** but still **dependent**.  

Example: Let  
$X \sim N(0,1), \quad Y = X^2$

- Correlation between X and Y = 0 (no linear relationship).  
- But Y is completely determined by X (they are dependent).

"""

x = np.random.normal(0, 1, 1000)
y = x**2

plt.scatter(x, y, alpha=0.3)
plt.title("X vs Y = X^2")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

np.corrcoef(x, y)[0, 1]

"""### Exercise 2
Try another example: define `Y = cos(X)` for `X` sampled uniformly from [-π, π].  
- Plot `X` vs `Y`.  
- Compute the correlation coefficient.  
- Are X and Y independent? Why or why not?

"""

# Your code here

x = np.arange(-np.pi, np.pi, .05)
# print(x)
y = np.sin(x)

plot = plt.scatter(x,y)
cc = np.corrcoef(x,y)[1,0]

print(cc)

"""## 3. Simpson’s Paradox

Simpson’s Paradox occurs when a trend appears in different groups of data but reverses when the groups are combined.

Example: University admissions data:  

- Group A (Men vs Women): higher female admit rate  
- Group B (Men vs Women): higher female admit rate  
- Combined: women appear to have lower admit rate  

"""

import pandas as pd

# Simulated data
data = pd.DataFrame({
    "Department": ["A"]*100 + ["B"]*100,
    "Gender": ["M"]*80 + ["F"]*20 + ["M"]*20 + ["F"]*80,
    "Admitted": [1]*60 + [0]*20 + [1]*15 + [0]*5 + [1]*10 + [0]*10 + [1]*40 + [0]*40
})

# Grouped admit rates
print(data.groupby(["Department", "Gender"])["Admitted"].mean())
print("\nOverall rates:")
print(data.groupby("Gender")["Admitted"].mean())

"""### Exercise 3
1. Interpret the paradox in the example above.  
2. Why does the paradox occur?  
3. Provide one real-world situation where Simpson’s Paradox could mislead decision-making.

We see that in each department, the proportion of males that are admitted exactly equals the proportion of females that are admitted.

The paradox is that we see that despite all proportions we see being identical, the total female admittance rate is lower than the total male admittance rate.

This is actually occurring because more women compose the "low proportion group" than do men, and less women compose the "high proportion group" than do men.

In the end, the low proportion group is heavily weighted, so in a weighted average, women will have a lower average admittance rate.

A real-world situation is in fast food.

A government is trying to decide whether or not to break up a monopoly... say McDonalds. We know that McDonalds has the best business in the country as a whole. But in court, its lawyers show a map of "the most popular fast food restaurants by state," and McDonalds is not on a single state. Clearly, McDonalds couldn't have a monopoly! (This is true btw I saw in on linkedin)
"""