# -*- coding: utf-8 -*-
"""Copy of cs473_lab_week_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KSaDU0ispBIGOumozjXv1esQ3S6HDGF

<a href="https://colab.research.google.com/github/wingated/cs473/blob/main/labs/cs473_lab_week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a><p><b>After clicking the "Open in Colab" link, copy the notebook to your own Google Drive before getting started, or it will not save your work</b></p>

# BYU CS 473 Lab Week 2

## Introduction:
Welcome to your first lab for CS 473, Advanced Machine Learning.

In machine learning, models often predict *unnormalized log probabilities*. These must often be converted into regular probabilities.

In this lab, you will explore the log-sum-exp function, which is described in the text (Sec. 2.5.4).  You will code up several variants of the function, and compare their performance.

# Part 1: Logsumexp
---
## Setup: The Iris Dataset
We'll begin by downloading the Iris dataset. The iris dataset is a simple, but very famous, dataset introduced to the world by RA Fisher (the “father” of modern statistics”) in 1939. The dataset has five columns:
* sepal length (cm)
* sepal width (cm)
* petal length (cm)
* petal width (cm)
* class

In order to get logits to play with, we'll first train a multinomial logistic regression model (Sec. 2.5.3).  This model naturally outputs logits.
"""

import datasets
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

ds = datasets.load_dataset( "scikit-learn/iris" )

df = pd.DataFrame( ds['train'] )

X = np.array( df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']] )
Y = np.array( LabelEncoder().fit_transform( df['Species'] ) )

from sklearn.linear_model import LogisticRegression

model = LogisticRegression().fit(X,Y)

W = model.coef_
b = model.intercept_

b = np.reshape( b, (3,1))

logits = np.dot( W, X.T ) + b

"""---
## Exercise 1: convert logits to probabilities

Since our model outputs logits, they must be converted. To do this, we'll use the softmax function.
"""

def softmax( logits ):
    # logits is a numpy matrix of d x N
    # where
    #   d is the number of classes
    #   N is the number of data points
    # use equation 2.99 (see also Eq. 2.94)

    #first we are going to find the max(a_sub_n) so we can subtract it from
    # every other value

    # max_a = np.max(logits)

  # #^this didn't work beecause we want max per row
  #   # print(max_a)

  #   #define a function that gives you one normalized logit,
  #   #by running through the whole vector of logits, using lse-trick

  #   def lse(i, vec_a):
  #     max_a_per_columns = max(vec_a, axis=0)
  #     return vec_a[i]/(max_a + np.log(np.sum(np.exp(vec_a-max_a))))

  #   #define a list that will turn into an array
  #   sm = []

  #   #add to the list with lse function
  #   for i in range(len(logits[0])):
  #     sm.append(
  #         lse(i, logits, max_a)
  #     )

  #   #turn into an array!
  #   normalized_logits = np.array(sm)

  #   # your code here
#-----------------------------------------ignore that stuff. i have learned better.
    exp_logits = np.exp(logits)

    Z = np.sum(exp_logits, axis=0, keepdims=True)

    probs = exp_logits/Z

    return probs

# print out test cases
probs = softmax(logits)

probs[:,0]

# probs[:,120]

"""### test cases
probs = softmax( logits )
probs[:,0]
#### array([9.81803910e-01, 1.81960759e-02, 1.43430317e-08])
probs[:,120]
#### array([5.49519371e-06, 2.38812718e-02, 9.76113233e-01])

---
## Exercise 2: convert logits to probabilities

Now, code up the logsumexp function.  What test cases should you use for this function?
"""

def logsumexp( logits ):
    # logits is a numpy matrix of d x N
    # where
    #   d is the number of classes
    #   N is the number of data points
    # use equation 2.100

    exp_logits = np.exp(logits)

    max_logits = np.max(logits, axis=0, keepdims=True)

    # def lse(a):
    #   lse =

    #   return lse
    m_logits = logits - max_logits

    sum_exp = np.sum(np.exp(m_logits), axis=0, keepdims=True)
    lse_val = max_logits + np.log(sum_exp)

    probs = np.exp(logits - lse_val)

    # your code here
    return probs

# test cases
probs = logsumexp( logits )
probs[:,0]
probs[:,120]

"""What should be printed??

The same thing that our original softmax function printed! its mathematically equivalent!

---
## Exercise 3: explore underflow / overlow

First, code up a function that compares two distributions. This can be anything you want; you may consider things like the MSE.
"""

def compare_probs( probs1, probs2 ):
    # p1_sum = pd.probs1.describe()
    # p1_sum = pd.probs1.describe()

    mse = np.mean((probs1 - probs2)**2)

    return mse

probs1 = softmax( logits )
probs2 = logsumexp( logits )
compare_probs( probs1, probs2 )

"""Now, see what happens if you add (or subtract) a constant from logits. How big must the constant be before things start going haywire?"""

# your code here
C = 700

probs1 = softmax( logits + C )

compare_probs(probs1, probs2)

"""We could add a constant up to 700 exactly before we got NaN.

Now convert the logits to 16-bit precision, and re-run your experiments. Analyze the differences you see (2-3 sentences).
"""

logits = logits.astype( np.float16 )

D = 2
# your code here
probs1 = softmax( logits + D )
# etc.

compare_probs(probs1,probs2)

"""### Analysis

Okay, so we see the constant that can be added to the softmax function is limited to ONLY 2!!!!. Why is this? When we only have 16 bits, both over- and under- flow is much easier to obtain. we just don't have the memory to have larger numbers from adding a constant to the non-logsumexp function

---
## Exercise 4: cleanly compute log probabilities

Sometimes, we want to compute log probabilities (which are different from logits), but we want to do so "cleanly", ie, while avoiding overflow / underflow. First, mathematically figure out what the log of the softmax is (ie, take the log of eq. 2.99), and then combine it with insights from coding up the logsumexp function. Hint: at the end of the day, you will simply shift each column by a per-column constant!
"""

def log_logsumexp( logits ):
    # logits is a numpy matrix of d x N
    # where
    #   d is the number of classes

    #   N is the number of data points
    max_logits = np.max(logits, axis=0, keepdims=True)

    m_logits = logits - max_logits

    lse = max_logits + np.log(np.sum(
      np.exp(m_logits),
      axis=0, keepdims=True)
    )

    shifted = logits - lse

    return shifted



"""---
# Part 2: Probability Fundamentals

For the following exercises, you are encouraged to work both by hand and by code however makes the most sense.

## Exercise 1a: Joint Probability Distributions

You are given the following two binary variables, X and Y, that can each take on the values 0 or 1. Assuming X and Y are independent, calculate the joint probability table (2x2 table for P(X, Y)). Display as a numpy array.

P(X=0) = 0.6

P(X=1) = 0.4

P(Y=0) = 0.7

P(Y=1) = 0.3
"""

# Rows are X (0, 1), Cols are Y (0, 1)
table = np.array([
    [0.42, 0.18],
    [0.28, 0.12]
])

"""Next, compute the following conditional probabilities:

P(X=0|Y=0) = .42 * (1/(.42+.28)) = .6

P(X=0|Y=1) = .18 * (1/(.18+.12)) = .6

P(Y=0|X=0) = .42 * (1/(.42+.18)) = .7

P(Y=0|X=1) = .28 * (1/(.28+.12)) = .7
"""

# Your code here

#

"""Compare the result of these conditional probabilities to the original marginal probabilities given. What does this say about the relationship between variable dependence and using conditional probabilities? Write 1-2 sentences.

When two variables are independent, they have no causal relationship. they may have correlation, but in this universe there are only two random variables. Conditional probability is identical to regular probability because there is no relationship between them.

## Exercise 1b: Joint Probability Distributions

Now consider this joint distribution:

|  | $Y = 0$ | $Y = 1$|
| :------- | :------: | -------: |
| $X = 0$  | 0.45  | 0.10  |
| $X = 1$  | 0.25  | 0.20  |

First, compute the marginals from the joint table
"""

joint_prob_table = np.array([[0.45, 0.10],
                             [0.25, 0.20]])

# P(X=0) = .55
# P(X=1) = .45
# P(Y=0) = .7
# P(Y=1) = .3

# Your answer here

"""Compute the same conditional probabilities as above:

P(X=0|Y=0) = .6429

P(X=0|Y=1) = .3333

P(Y=0|X=0) = .8182

P(Y=0|X=1) = .5556
"""

# P(X=0|Y=0) = .6429
# P(X=0|Y=1) = .3333
# P(Y=0|X=0) = .8182
# P(Y=0|X=1) = .5556

# Your answer here

"""Check if the independence property $P(X, Y) = P(X)P(Y)$ holds for any cell."""

# Cell (X=0, Y=0)
# P(X=0,Y=0) = .45
# P(X=0) * P(Y=0) = .55 * .7 = .385
#  fails (.45 != .385)

# Cell (X=0, Y=1)
# P(X=0,Y=1) = .10
# P(X=0) * P(Y=1) = .55 * .3 = .165
#  fails (.10 != .165)

# Cell (X=1, Y=0)
# P(X=1,Y=0) = .25
# P(X=1) * P(Y=0) = .45 * .7 = .315
#  fails (.25 != .315)

# Cell (X=1, Y=1)
# P(X=1,Y=1) = .20
# P(X=1) * P(Y=1) = .45 * .3 = .135
#  fails (.20 != .135)

"""The property DOES NOT hold

Compare P(X=0|Y=0) to P(X=0|Y=1), and discuss what this says about the dependence between these variables (1-2 sentences).

<br>
X has higher  chance of being 0 when Y is 0. So they are positively correlated. (positive beta)

---
## Exercise 2: Bayes Theorem

After your yearly checkup, the doctor has bad news and good news. The bad news is that you tested positive
for a serious disease, and that the test is 99% accurate (i.e., the probability of testing positive given that you
have the disease is 0.99, as is the probability of testing negative given that you don’t have the disease). The
good news is that this is a rare disease, striking only one in 10,000 people. What are the chances that you
actually have the disease? (Show your calculations as well as giving the final result.)

*Hint: write out the variables you know, and think about what you'll need to calculate to find the final answer
"""

# vars
pd = 1 / 10000
pnd = 1 - pd
pos_given_d = .99
neg_given_nd = .99

# false pos rate
pos_given_nd = 1 - neg_given_nd

# total prob of positive test
# p(pos) = true pos + false pos
p_pos = (pos_given_d * pd) + (pos_given_nd * pnd)

# bayes stuff
# p(disease | pos)
ans = (pos_given_d * pd) / p_pos

print(f"chance u have it: {ans:.4f}")
# output: 0.0098