# -*- coding: utf-8 -*-
"""Copy of week_5_bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aix9wNKdhQtK5szZ5RUJDVamw5zoV2ke

<a href="https://colab.research.google.com/github/wingated/cs473/blob/main/mini_labs/week_5_bayes.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# BYU CS 473 — Bayes Law and the Beta-Binomial model

In this assignment, you will learn more intuition for priors, posteriors, and the role that data plays in our inferences about a latent hypothesis.

---

## Learning Goals
- Understand priors and posteriors
- Understand the beta-binomial model
- Understand how data eventually overwhelms the prior

## 1. Exploring the beta prior

The beta distribution is a continuous distribution over the interval [0,1].  Because this is exactly the domain of a single probability (such as the probability that a coin will come up heads), it can be used as a prior distribution over an unknown parameter.  To start, let's plot it for various values of its two parameters, which we will call (a) and (b).
"""

import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import beta

# Test various values of alpha and beta
parameter_values = [
    (1, 1),
    (1, 10),
    (10, 1),
    (10, 10),
    (0.1, 0.1),
    (100,100)
]

xvals = np.linspace(0, 1, 100)

# Plot the beta prior for each value of beta
for a, b in parameter_values:
    yvals = beta.pdf( xvals, a, b )
    plt.plot(xvals, yvals, label=f"Beta={a}, {b}" )

plt.legend()
plt.title("Beta Prior")
plt.show()

"""### Reflection
- Consider the beta distribution defined by each setting of the parameters (a) and (b). Which is the most uniform? Which is the most confident? Which is binary?

### TODO: write your answer here
We know that a-1 == num successes, b-1==num failures. It makes a lot of sense that 0 successes and 0 failures has the most uniform beta dist.

The most confident is definitely brown (beta(100,100)), because it is working off of 198 trials. You can see the height of the hill and the width of the hill are the tallest and skinniest of all.

"Binary" is an interesting term here because none of them have ONLY delta functions at 0 and 1 (and nothing in between), but the closest thing to that is beta(0.1,0.1) because it is low in the middle and high on both sides. This is very weird and I don't understand how we even have 0.2 total trials.

## 2. Calculating the posterior

Given a prior defined by parameters (a) and (b), and some data, we'd now like to calculate (and visualize) the posterior distribution.

### Exercise 2

Suppose we have a coin that is weighted, but we don't know the weight. Call the unknown weight $\theta$.

Suppose now we flip the coin 10 times, and we see "HHTTHTHHHH".

Your task is to visualize how that data would affect our belief about $\theta$, given an initial belief about $\theta$.

To do this, you must do the following:

- For each of the prior parameter values in the list of parameter values from Part 1, calculate the posterior distribution $p(\theta|data)$
- Create a new figure for each setting of the prior parameter values.
- Plot the prior distribution, and the corresponding posterior, on the same figure.  (When you're done, you should have six figures, each with two plots)
"""

plt.figure()

# Plot the beta prior for each value of beta
plt_index = 0

#likelihood in order heads, tails
def likelihood(theta,h,t):
  return (
      (theta**h) * ((1-theta)**t)

  )

for a, b in parameter_values:
    plt_index += 1
    plt.subplot( 6, 1, plt_index )
    plt.title( f"Beta={a}, {b}" )

    # this is the prior, as calculated in part 1
    yvals = beta.pdf( xvals, a, b )
    plt.plot(xvals, yvals, label=f"Beta={a}, {b}" )


    prior = yvals

    post_y = beta.pdf(xvals, a+7, b+3)


    plt.plot(xvals, post_y, label=f'Posterior for Beta ={a}, {b}')
    # plt.legend()

    # now calculate the posterior, and plot it
    # XXX your code here

plt.show()

"""## 3. Reflection

### Exercise 3
Answer in 2–3 sentences each:

1. Which prior was the "strongest" (ie, changed the least in response to seeing new data)? Which was the "weakest"?
2. Suppose you wanted to create a prior that was very confident about the value of $\theta$. How would you do that?
3. What would an "infinitely strong" prior look like?

1. It looks like the prior of beta=100,100 was the strongest. It barely moved at all. This is because adding 7 to 100 and 3 to 100 pretty much does nothing.

The weakest prior, that moved the most, was arguably the binary prior beta(0.1,0.1). This became low where it was high, and high where it was low.

2.A confident prior would have to have a large value in at least one parameter of beta.pdf(a,b). This way, addition of the likelihood into the parameters has essentially no marginal effect. Again, we get to say this because the prior and posterior are members of the same hypothesis family.

3. An "infinitely strong" prior would be composed of np.inf() in either the alpha and/or the beta parameters. This makes it so any addition to either parameter is basically zero.
"""